name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.11.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
#      - name: Build production project
#        run: npm run build:prod
      - name: Linting typescript
        run: npm run lint:ts
      - name: Linting css
        run: npm run lint:scss
      - name: Jest testing
        run: npm run test:jest
      - name: Build storybook
        run: npm run storybook:build
      - name: Loki screenshot testing in storybook
        run: npm run test:loki